import axios from 'axios';

export const generateSongList = async (topic) => {
  try {
    const response = await axios.post(
      'https://api.openai.com/v4/engines/davinci-codex/completions',
      {
        prompt: `Generate a list of song titles about ${topic}`,
        max_tokens: 60,
      },
      {
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${process.env.REACT_APP_OPENAI_API_KEY}`
        },
      }
    );

    // Extract the song titles from the response
    const songTitles = response.data.choices[0].text.split('\n');

    return songTitles;
  } catch (error) {
    console.error('Error generating song list:', error);
    return [];
  }
};

export const createPlaylist = async (songTitles) => {
  try {
    const response = await axios.post(
      'https://api.spotify.com/v1/users/{user_id}/playlists',
      {
        name: 'Generated Playlist',
        description: 'This playlist was generated by our app.',
        public: false,
        tracks: songTitles.map((title) => ({ name: title })),
      },
      {
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${process.env.REACT_APP_SPOTIFY_API_KEY}`
        },
      }
    );

    // Extract the playlist URL from the response
    const playlistUrl = response.data.external_urls.spotify;

    return playlistUrl;
  } catch (error) {
    console.error('Error creating playlist:', error);
    return '';
  }
};

